import pygame
from script import load_image
fon_image = load_image('image/fon')
player_1_idle_image = load_image('image/player1/idle')
player_1_attack1_image = load_image('image/player1/attack1')
player_1_run_image = load_image('image/player1/run')
player_1_attack2_image = load_image('image/player1/attack2')
player_2_attack_image = load_image('image/player2/attack')
player_2_idle_image = load_image('image/player2/idle')
player_2_run_image = load_image('image/player2/run')
player_3_idle_image = load_image('image/player3/idle')
player_3_run_image = load_image('image/player3/run')
player_3_atck_image = load_image('image/player3/atck')
player_3_atck2_image = load_image('image/player3/atck2')
player_3_death_image = load_image('image/player3/death')
player_4_idle_image = load_image('image/player4/idle')
player_4_run_image = load_image('image/player4/run')
player_4_atck_image = load_image('image/player4/atck')
player_4_atck2_image = load_image('image/player4/atck2')
player_4_death_image = load_image('image/player4/death')